### ISSUE TITLE
找不到jshare_file_provider_paths

### ISSUE THREAD

**Issue by tobqzxc** [jpush/jshare-flutter-plugin#25]

**Comment by tobqzxc** [comment]
![image](https://user-images.githubusercontent.com/23162218/142796338-db693cd2-2721-4fb4-b176-53c2d5f2780f.png)

**Comment by xiaoxuacr** [comment]
插件example里有
![image](https://user-images.githubusercontent.com/19487786/158294664-08e0744d-8430-4615-b421-ae229001bca2.png)
